using Test
using RegularizationAndGlobalOptimizationInModelBasedClustering
RegularizationAndGlobalOptimizationInModelBasedClustering.initialize()

RegularizationAndGlobalOptimizationInModelBasedClustering.main([])